image: ruby:2.6.5

variables:
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"
  CI: "true"
  PGUSER: "postgres"
  PGPASSWORD: "postgres"
  PGHOST: "postgres"
  PGPORT: 5432
  POSTGRES_HOST_AUTH_METHOD: "trust"

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - vendor/bundle/

services:
  - postgres:12.2-alpine

before_script:
  - ./gitlab-ci/setup.sh

stages:
  - test

rspec:
  stage: test
  script:
    - ./gitlab-ci/rspec.sh
